### ISSUE TITLE
Terraboard charts latest version not available

### ISSUE THREAD

**Issue by cnguyen383** [camptocamp/charts#55]
Recently, there have been an updated to Terraboard chart -> https://github.com/camptocamp/charts/pull/54. However this new version has not actually been published yet. 

```
│ Error: chart "terraboard" version "2.1.0" not found in https://camptocamp.github.io/charts repository
│
│   with helm_release.terraboard,
│   on helm.tf line 47, in resource "helm_release" "terraboard":
│   47: resource "helm_release" "terraboard" {
│
```

Please do the needful and push the latest version to the chart repo @hbollon

**Comment by cnguyen383** [comment]
```
❯ helm search repo c2c/terraboard
NAME          	CHART VERSION	APP VERSION	DESCRIPTION
c2c/terraboard	2.0.3        	2.0.0      	A web interface for Terraform states
```
confirmed that the latest version, `2.1.0`, is not pushed.

**Comment by hbollon** [comment]
@cnguyen383 It should be good now, sorry for the omission
